In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
crime_df = pd.read_csv("age_crime.csv")
crime_df

,Year,Year ending,Sex,Age Group,Offence Division,Alleged Offender Incidents
0,2021,December,Females,10-14 years,A Crimes against the person,657
1,2021,December,Females,10-14 years,B Property and deception offences,557
2,2021,December,Females,10-14 years,C Drug offences,21
3,2021,December,Females,10-14 years,D Public order and security offences,53
4,2021,December,Females,10-14 years,E Justice procedures offences,47
...,...,...,...,...,...,...
1546,2012,December,Males,65 years and over,B Property and deception offences,321
1547,2012,December,Males,65 years and over,C Drug offences,31
1548,2012,December,Males,65 years and over,D Public order and security offences,165
1549,2012,December,Males,65 years and over,E Justice procedures offences,123
1550,2012,December,Males,65 years and over,F Other offences,8

In [3]:
cols = []
for col in crime_df.columns:
    cols.append(col)
    print(col)

Year
Year ending
Sex
Age Group
Offence Division
Alleged Offender Incidents

In [4]:
crime_df["Alleged Offender Incidents"].describe()

count     1551
unique    1005
top          2
freq        31
Name: Alleged Offender Incidents, dtype: object

In [5]:
crime_df.dtypes

Year                           int64
Year ending                   object
Sex                           object
Age Group                     object
Offence Division              object
Alleged Offender Incidents    object
dtype: object

In [10]:
crime_df['Incidents_cleaned'] = crime_df['Alleged Offender Incidents']
crime_df["Incidents_cleaned"] = crime_df["Incidents_cleaned"].replace(",","", regex = True)
crime_df

,Year,Year ending,Sex,Age Group,Offence Division,Alleged Offender Incidents,Incidents_cleaned
0,2021,December,Females,10-14 years,A Crimes against the person,657,657
1,2021,December,Females,10-14 years,B Property and deception offences,557,557
2,2021,December,Females,10-14 years,C Drug offences,21,21
3,2021,December,Females,10-14 years,D Public order and security offences,53,53
4,2021,December,Females,10-14 years,E Justice procedures offences,47,47
...,...,...,...,...,...,...,...
1546,2012,December,Males,65 years and over,B Property and deception offences,321,321
1547,2012,December,Males,65 years and over,C Drug offences,31,31
1548,2012,December,Males,65 years and over,D Public order and security offences,165,165
1549,2012,December,Males,65 years and over,E Justice procedures offences,123,123
1550,2012,December,Males,65 years and over,F Other offences,8,8

In [13]:
crime_df["Incidents_cleaned"].astype('float')

0       657.0
1       557.0
2        21.0
3        53.0
4        47.0
        ...
1546    321.0
1547     31.0
1548    165.0
1549    123.0
1550      8.0
Name: Incidents_cleaned, Length: 1551, dtype: float64

In [23]:
crime_df.astype({'Incidents_cleaned':'float'})

,Year,Year ending,Sex,Age Group,Offence Division,Alleged Offender Incidents,Incidents_cleaned
0,2021,December,Females,10-14 years,A Crimes against the person,657,657.0
1,2021,December,Females,10-14 years,B Property and deception offences,557,557.0
2,2021,December,Females,10-14 years,C Drug offences,21,21.0
3,2021,December,Females,10-14 years,D Public order and security offences,53,53.0
4,2021,December,Females,10-14 years,E Justice procedures offences,47,47.0
...,...,...,...,...,...,...,...
1546,2012,December,Males,65 years and over,B Property and deception offences,321,321.0
1547,2012,December,Males,65 years and over,C Drug offences,31,31.0
1548,2012,December,Males,65 years and over,D Public order and security offences,165,165.0
1549,2012,December,Males,65 years and over,E Justice procedures offences,123,123.0
1550,2012,December,Males,65 years and over,F Other offences,8,8.0

In [58]:
age_10_14_df = crime_df.loc[crime_df['Age Group'] == '10-14 years']
total_10_14 = age_10_14_df.groupby(['Year','Sex'])["Incidents_cleaned"].sum()

age_15_17_df = crime_df.loc[crime_df['Age Group'] == '15-17 years']
total_15_17 = age_15_17_df.groupby(['Year','Sex'])["Incidents_cleaned"].sum()

age_18_19_df = crime_df.loc[crime_df['Age Group'] == '18-19 years']
total_18_19 = age_15_17_df.groupby(['Year','Sex'])["Incidents_cleaned"].sum()

age_20_24_df = crime_df.loc[crime_df['Age Group'] == '20-24 years']
total_20_24 = age_20_24_df.groupby(['Year','Sex'])["Incidents_cleaned"].sum()

age_25_29_df = crime_df.loc[crime_df['Age Group'] == '25-29 years']
total_25_29 = age_25_29_df.groupby(['Year','Sex'])["Incidents_cleaned"].sum()

age_30_34_df = crime_df.loc[crime_df['Age Group'] == '30-34 years']
total_30_34 = age_30_34_df.groupby(['Year','Sex'])["Incidents_cleaned"].sum()

age_35_39_df = crime_df.loc[crime_df['Age Group'] == '35-39 years']
total_35_39 = age_35_39_df.groupby(['Year','Sex'])["Incidents_cleaned"].sum()

age_40_44_df = crime_df.loc[crime_df['Age Group'] == '40-44 years']
total_40_44 = age_40_44_df.groupby(['Year','Sex'])["Incidents_cleaned"].sum()

age_45_49_df = crime_df.loc[crime_df['Age Group'] == '45-49 years']
total_45_49 = age_45_49_df.groupby(['Year','Sex'])["Incidents_cleaned"].sum()

age_50_54_df = crime_df.loc[crime_df['Age Group'] == '50-54 years']
total_50_54 = age_50_54_df.groupby(['Year','Sex'])["Incidents_cleaned"].sum()

age_55_59_df = crime_df.loc[crime_df['Age Group'] == '55-59 years']
total_40_44 = age_40_44_df.groupby(['Year','Sex'])["Incidents_cleaned"].sum()

age_60_64_df = crime_df.loc[crime_df['Age Group'] == '60-64 years']
total_60_64 = age_60_64_df.groupby(['Year','Sex'])["Incidents_cleaned"].sum()

age_65_over_df = crime_df.loc[crime_df['Age Group'] == '65 years and over']
total_65_over = age_65_over_df.groupby(['Year','Sex'])["Incidents_cleaned"].sum()